apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "node-hello.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-hello.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: node-hello.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "node-hello.fullname" . }}
            port:
              number: 8080
