name: Docker build & push

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    
    - name: Check out node-hello repo
      uses: actions/checkout@master
      with:
        repository: a12com/dr_test

    - name: Extract branch name
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short=6 HEAD)"
      id: commit

    - name: Build node-hello docker image
      run: docker build -t node-hello .
      working-directory: ./images/node

    - name: Run docker image
      run: docker run -d -p 8888:8888 node-hello

    - uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm ci
      working-directory: ./test

    - name: Run tests
      run: npm test
      working-directory: ./test

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker tag
      run: |
       docker tag node-hello ${{ secrets.DOCKERHUB_USERNAME }}/node-hello:latest
       docker tag node-hello ${{ secrets.DOCKERHUB_USERNAME }}/node-hello:${{ steps.commit.outputs.sha_short }}-${{ github.run_number }}

    - name: Push docker image
      run: |
       docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-hello:latest  
       docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-hello:${{ steps.commit.outputs.sha_short }}-${{ github.run_number }}
