name: Docker build & push

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
    - name: Check out node-hello repo
      uses: actions/checkout@master
      with:
        repository: a12com/dr_test

    - name: List files
      run: ls -lahr
